version: "3"
services:
  apache:
    container_name: "apache"
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./wp:/var/www/html/apps/wp/
      - ./containers/apache2/sites-available:/etc/apache2/sites-available
      - ./logs:/var/log/apache2
  db:
    container_name: "db"
    image: mysql:5.6.36
    ports:
      - "3306:3306"
    env_file: containers/db/.env
    volumes:
      - "./containers/db/init/local:/docker-entrypoint-initdb.d"
